### ISSUE TITLE
Rendering Issue about HiQ Chinese Documentation

### ISSUE THREAD

**Issue by Neuromancer43** [Huawei-HiQ/HiQsimulator#14]
The HiQ Chinese Documentation can't correctly render \LaTeX math formula. (while the English version is good)

![image](https://user-images.githubusercontent.com/20223932/61603537-8a699280-ac70-11e9-8788-e2aeaafa588b.png)

![image](https://user-images.githubusercontent.com/20223932/61603608-c7358980-ac70-11e9-9fa3-41d8876779b4.png)

**Comment by berryboy2012** [comment]
出现这个问题的原因是中文版文档的web服务器返回的header有着更为严格的内容安全策略，导致从cloudflare加载的mathjax.js无法正常渲染数学公式，这个问题在本repo无法解决。
