### ISSUE TITLE
Meetup plan -- Guangzhou soon

### ISSUE THREAD

**Issue by i2000s** [Huawei-HiQ/HiQsimulator#21]
Just chatted with a few friends on WeChat, and concluded that we could host a meetup at Guangzhou. I can give a tutorial talk on ProjectQ and HiQ for beginners (Damien, your contribution as well), if interested. Please respond below if you can give a talk or would like to participate. Also, suggest a time slot that works best for you. Or, comment with anything else. 

PS: each talk can be 10-30mins, free style. Class room doesn't seem to be a problem for now. :-)

**Comment by QPIpattern** [comment]
September is OK for me. I can give a talk on how to use ProjectQ and openfermion to solve some quantum chemistry problems.

**Comment by Takishima** [comment]
Happy to help in anyway I can

**Comment by luoml5** [comment]
Can I participate in this activity as a listener or volunteer ?  I'm a green hand on ProjectQ and HIQ. Thanks.

**Comment by guochu** [comment]
September is ok for me. I can just drop by, or talk about some general stuff about how to implement   easy-to-use variational quantum circuit using julia and Zygote .

**Comment by Benature** [comment]
It will be nice if the meetup will be at the weekend :)

**Comment by i2000s** [comment]
Im not sure about Sep now. Other time?
