### ISSUE TITLE
fail to run examples

### ISSUE THREAD

**Issue by tom-shan** [Huawei-HiQ/HiQsimulator#31]
I failed to run almost every examples in this repo following the [tutorial](https://hiqsimulator.readthedocs.io/en/latest/tutorials/tutorials.local.html)
![image](https://user-images.githubusercontent.com/7686800/70997428-0aa4fe80-2110-11ea-9357-0790f2ce2e46.png),
and only the running of ToeplitzSimplify_constant.py is successful.

I also tried to follow these lines in [.travis.yml](https://github.com/Huawei-HiQ/HiQsimulator/blob/174a823973a97e8264ae7d412ee4c5d52e7d713d/.travis.yml#L52-L59),
but still failed to run `make -j2 build_all_test`.
![image](https://user-images.githubusercontent.com/7686800/70997947-0f1de700-2111-11ea-9379-d46eec4ead7e.png)

my machine os:  ubuntu 18.04

**Comment by DechinPhy** [comment]
I have the same problem in testing installation of HiQsimulator. Though the installation process is very success. But the version of HiQsimulator I installed half month ago works correctly. I just do not know why for now because there are none of new commits these days.

**Comment by tom-shan** [comment]
> I have the same problem in testing installation of HiQsimulator. Though the installation process is very success. But the version of HiQsimulator I installed half month ago works correctly. I just do not know why for now because there are none of new commits these days.

I think it may be caused by dependencies updates, for these dependencies in https://github.com/Huawei-HiQ/HiQsimulator/blob/master/requirements.txt are not fixed.

**Comment by DechinPhy** [comment]
> > I have the same problem in testing installation of HiQsimulator. Though the installation process is very success. But the version of HiQsimulator I installed half month ago works correctly. I just do not know why for now because there are none of new commits these days.
> 
> I think it may be caused by dependencies updates, for these dependencies in https://github.com/Huawei-HiQ/HiQsimulator/blob/master/requirements.txt are not fixed.

How about try to import hiq based packages before projectq packages? Will this help you in this bug? It does work for me.

**Comment by tom-shan** [comment]
Thanks for your suggestion.
If I import hiq based packages at the first few lines of example scripts, then this issue is fixed. 
Could you provide an explanation about why it can work?

**Comment by i2000s** [comment]
This relates to some environmental conflict problem between ProjectQ and HiQ packages. This may be fixed in our fork of ProjectQ.
