### ISSUE TITLE
Can HiQ work on the cluster of GPUS?

### ISSUE THREAD

**Issue by amandalqy** [Huawei-HiQ/HiQsimulator#36]

**Comment by Takishima** [comment]
Dear @amandalqy,
At the time of this writing, the code does have support for offloading some of the computations on GPUs. It will therefore not be able to benefit from running on a cluster of GPUs.
However, this is a feature we are looking to implement some time in the future. If you would like to get involved, please get in touch with us so we can discuss things in more details.

**Comment by amandalqy** [comment]
@Takishima, thanks a lot!

**Comment by amandalqy** [comment]
@Takishima ,thanks for your invitation! Unfortunately, I don't have enough time to get involved in  running HiQ on a cluster of GPUs recently, sorry!
