### ISSUE TITLE
Does the  Huawei-HiQ / HiQsimulator support Single amplitude simulator？

### ISSUE THREAD

**Issue by amandalqy** [Huawei-HiQ/HiQsimulator#37]

**Comment by amandalqy** [comment]
In the Tutorials,the section"Use HiQsimulator as backends" doesn't give any example of Single amplitude simulator .So is single amplitude simulator open in HiQsimulator ? Can we accomplish Single amplitude simulator through  HiQsimulator?

**Comment by yzotov** [comment]
There is no single amplitude simulator within HiQSimulator. 
HiQSimulator has distributed memory full state vector simulator and stabilizer simulator.
