### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yangguohao** [Huawei-HiQ/HiQsimulator#50]
**Describe the bug**
I am quite confused about the example of grover algorithm in maximum_search_constant_mpi.py

**Screenshots**
![image](https://user-images.githubusercontent.com/70266361/190105944-16ab9afb-b99b-4c28-9de3-cda9a0eba0f2.png)

**Additional context**
The 'num1' is the shallow copy of num so when the 'num1' list being modified, the 'num' list will be modified too. Therefore the X gates that come after didn't apply on the circuit. Is this a mistake or the design of oracle.

**Comment by Takishima** [comment]
This does look like an error and what was probably intended was to do a deep copy of num as you guessed.

**Comment by yangguohao** [comment]
> This does look like an error and what was probably intended was to do a deep copy of num as you guessed.

OK, thanks for reply
