### ISSUE TITLE
Compile hiqsimulator  on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by Huawei-HiQ** [Huawei-HiQ/HiQsimulator#8]
quantum@ubuntu-157:~/XXX/HiQsimulator-master$ cat /proc/version
    Linux version 4.15.0-55-generic (buildd@lcy01-amd64-029) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019
    quantum@ubuntu-157:~/XXX/HiQsimulator-master$ 
    quantum@ubuntu-157:~/XXX/HiQsimulator-master$ cmake -version
    cmake version 3.12.0
    
    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    quantum@ubuntu-157:~/XXX/HiQsimulator-master$ 
    quantum@ubuntu-157:/usr/lib/x86_64-linux-gnu$ sudo find ./ -name "libgflags.so"
    ./libgflags.so   
    quantum@ubuntu-157:~/XXX/HiQsimulator-maste
    quantum@ubuntu-157:~/XXX/HiQsimulator-maste
    quantum@ubuntu-157:~/XXX/HiQsimulator-master$ python3 setup.py build
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/hiq
    creating build/lib.linux-x86_64-3.6/hiq/projectq
    creating build/lib.linux-x86_64-3.6/hiq/projectq/backends
    copying hiq/projectq/backends/__init__.py -> build/lib.linux-x86_64-3.6/hiq/projectq/backends
    creating build/lib.linux-x86_64-3.6/hiq/projectq/backends/_sim
    copying hiq/projectq/backends/_sim/_stabilizer_simulator.py -> build/lib.linux-x86_64-3.6/hiq/projectq/backends/_sim
    copying hiq/projectq/backends/_sim/__init__.py -> build/lib.linux-x86_64-3.6/hiq/projectq/backends/_sim
    copying hiq/projectq/backends/_sim/_simulator_mpi.py -> build/lib.linux-x86_64-3.6/hiq/projectq/backends/_sim
    copying hiq/projectq/backends/_sim/_stabilizer_simulator_test.py -> build/lib.linux-x86_64-3.6/hiq/projectq/backends/_sim
    copying hiq/projectq/backends/_sim/_simulator_mpi_test.py -> build/lib.linux-x86_64-3.6/hiq/projectq/backends/_sim
    creating build/lib.linux-x86_64-3.6/hiq/projectq/ops
    copying hiq/projectq/ops/__init__.py -> build/lib.linux-x86_64-3.6/hiq/projectq/ops
    copying hiq/projectq/ops/_gates.py -> build/lib.linux-x86_64-3.6/hiq/projectq/ops
    creating build/lib.linux-x86_64-3.6/hiq/projectq/cengines
    copying hiq/projectq/cengines/_hiq_main_engine.py -> build/lib.linux-x86_64-3.6/hiq/projectq/cengines
    copying hiq/projectq/cengines/__init__.py -> build/lib.linux-x86_64-3.6/hiq/projectq/cengines
    copying hiq/projectq/cengines/_dummybackend.py -> build/lib.linux-x86_64-3.6/hiq/projectq/cengines
    copying hiq/projectq/cengines/_greedyscheduler.py -> build/lib.linux-x86_64-3.6/hiq/projectq/cengines
    running build_ext
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found OpenMP_CXX: -fopenmp (found version "4.5") 
    -- Found OpenMP: TRUE (found version "4.5")  
    -- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
    -- Found MPI: TRUE (found version "3.1")  
    -- Looking for C++ include pthread.h
    -- Looking for C++ include pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Boost version: 1.65.1
    -- Found the following Boost libraries:
    --   program_options
    --   mpi
    --   serialization
    --   thread
    --   chrono
    --   system
    --   date_time
    --   atomic
    -- Could NOT find glog (missing: glog_DIR)
    CMake Error at /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Failed to find the gflags library.  You might want to specify either the
      gflags_ROOT or gflags_DIR CMake variables.  (missing: gflags_LIBRARY)
    Call Stack (most recent call first):
      /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
      cmake/Findgflags.cmake:125 (find_package_handle_standard_args)
      cmake/Findglog.cmake:102 (find_package)
      cmake/packages.cmake:84 (find_package)
      CMakeLists.txt:59 (include)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/quantum/jiafei/HiQsimulator-master/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    See also "/home/quantum/jiafei/HiQsimulator-master/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "setup.py", line 140, in <module>
        packages=find_packages()
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "setup.py", line 56, in run
        self.build_extension(ext)
      File "setup.py", line 81, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/quantum/jiafei/HiQsimulator-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/quantum/jiafei/HiQsimulator-master/build/lib.linux-x86_64-3.6/hiq/projectq/backends/_sim', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON', '-DCMAKE_BUILD_TYPE=Release_MPI']' returned non-zero exit status 1.
    quantum@ubuntu-157:~/XXX/HiQsimulator-master$

**Comment by Takishima** [comment]
The problem is that CMake is not able to find the _gflags_ library since it is not in any known standard directory.

If you want to use a `libgflags.so` library that is located in the same folder, you would need to invoke CMake as follows:
    
    cmake -Dgflags_ROOT=$PWD ...

The same applies if you do not have the _glog_ library installed in any standard folder.

**Comment by Takishima** [comment]
This is really weird; the `libgflags.so` file is clearly present in `/usr/lib/x86_64-linux-gnu` and CMake should know how to look for it there.

Out of curiosity what is the version of _gflags_ that you have currently installed ? (`dpkg -l | grep gflags`)

**Comment by Takishima** [comment]
Ok, found the issue. I will submit a fix in a bit.

**Comment by Huawei-HiQ** [comment]
quantum@ubuntu-157:/usr/lib/x86_64-linux-gnu$ dpkg -l | grep gflags
ii  libgflags-dev                          2.2.1-1                           amd64        commandline flags module for C++ (development files)
ii  libgflags2.2                           2.2.1-1                           amd64        commandline flags module for C++ (shared library)

**Comment by keithyau** [comment]
![image](https://user-images.githubusercontent.com/659311/136753276-d779fa35-3262-4928-a9a8-a4069e168dcc.png)

same issue at ubuntu20.04

**Comment by Takishima** [comment]
I will need to look into this in more details to better understand what the issue is here with Ubuntu 20.04.
